config/routes.rb
Rails.application.routes.draw do

  resources :stickies, defaults: {format: :json}

  resources :rows, defaults: {format: :json}

  resources :columns, defaults: {format: :json} do
    collection do
      post :insert_between_columns
    end
  end

  resources :boards

  get 'boards/:uid' => 'boards#index'

  get 'landing_page' => 'welcome#landing_page'

  get 'create_board' => 'boards#create_board'

  root 'welcome#landing_page'

end

app/models/board.rb
class Board < ActiveRecord::Base

	has_many :columns
	has_many :rows

	before_create :generate_unique_uid

	after_create :create_default_parameters

	private
	def generate_unique_uid
		begin 
			self.uid = SecureRandom.urlsafe_base64
		end while Board.exists?(uid: self.uid)
	end


	def create_default_parameters
		Column.create(name: Board.human_attribute_name("todo"), column_order: 1, board_id: self.id)
		Column.create(name: Board.human_attribute_name("doing"), column_order: 2, board_id: self.id)
		Column.create(name: Board.human_attribute_name("done"), column_order: 3, board_id: self.id)
		Row.create(order: 1, board_id: self.id)
	end
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, only: [:edit, :update, :destroy]

  def index
    @boards = Board.all
  end

  def create_board
    @board = Board.create(name: t(:your_board))
    redirect_to '/boards/'+@board.uid
  end

  def show
    @board = Board.find_by_uid params[:id]
    redirect_to(root_url, :notice => 'Board not found') unless @board
  end

  def new
    @board = Board.new
  end

  def edit
  end

  def update

    respond_to do |format|
      if @board.update(board_params)
        format.html { redirect_to @board, notice: 'Board was successfully updated.' }
        format.json { render :show, status: :ok, location: @board }
      else
        format.html { render :edit }
        format.json { render json: @board.errors, status: :unprocessable_entity }
      end
    end
    
  end

  private

  def set_board
    @board = Board.find(params[:id])
  end

  def board_params
    params.require(:board).permit(:name, :uid)
  end

end

app/views/boards/_link_edit_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="linkEditModal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">

      <div class="modal-body">
      <form id="editLinkForm" class="form-horizontal">
          <fieldset>

            <!-- Form Name -->
            <legend>Add/Edit Link</legend>

            <!-- Text input-->
            <div class="form-group">
              <label class="col-md-4 control-label" for="link">Link</label>  
              <div class="col-md-5">
                <input id="link_input" name="link" type="text" placeholder="Insert a link" class="form-control input-md" required="">
              </div>
            </div>
            <input id="hiddenStickyId" type="hidden">

            <!-- Button (Double) -->
            <div class="form-group">
              <label class="col-md-4 control-label"></label>
              <div class="col-md-8">
                <a id="send" class="btn btn-primary"><span class="glyphicon glyphicon-check"></span> Submit</a>
                <a data-dismiss="modal" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span> Cancel</a>
              </div>
            </div>

          </fieldset>
        </form>

      </div>
    </div>
  </div>
</div>

app/views/boards/_stickie_option_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="stickieOptionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      
      <div class="modal-body">
        <h4><%= t(:select_color) %></h4>
        <div class="btn-group btn-group-lg btn-group-justified color-group">
          <a modal-color-class="panel-default" class="btn btn-default color-default">
            <span class="glyphicon glyphicon"></span>
          </a>
          <a modal-color-class="panel-success" class="btn btn-default color-success">
            <span class="glyphicon glyphicon"></span>
          </a>
          <a modal-color-class="panel-info" class="btn btn-default color-info">
            <span class="glyphicon glyphicon"></span>
          </a>
          <a modal-color-class="panel-warning" class="btn btn-default color-warning">
            <span class="glyphicon glyphicon"></span>
          </a>
          <a modal-color-class="panel-danger" class="btn btn-default color-danger">
            <span class="glyphicon glyphicon"></span>
          </a>
        </div>
        <hr/>
        <h4>Actions:</h4>
        <h4 class="data"></h4>
        <button type="button" class="btn btn-lg btn-primary btn-block modal-link">
          <span class="glyphicon glyphicon-link"></span> Link
        </button>
        <button type="button" class="btn btn-lg btn-primary btn-block modal-edit-link">
          <span class="glyphicon glyphicon-pencil"></span> Edit Link
        </button>
        <button type="button" class="btn btn-lg btn-danger btn-block modal-delete-stickie">
          <span class="glyphicon glyphicon-remove"></span> <%= t(:delete) %>
        </button>
      </div>
    </div>
  </div>
</div>

app/views/boards/show.html.erb
<% content_for :head do %>
<%= stylesheet_link_tag "boards", media: 'all', 'data-turbolinks-track' => true %>
<% end %>
<% content_for :title do %>
<title> <%= @board.name %> - eskra.me </title>
<% end %>

<%= render :partial => 'boards/stickie_option_modal' %>
<%= render :partial => 'boards/link_edit_modal' %>


<div class='container-fluid'>
  <div class="row">
    <div class="table-responsive">
      <table class="table table-bordered table-condensed">
        <thead class="title_field">
          <tr>
            <th><h4><%= t(:lanes) %></h4></th>
            <% @board.columns.order(:column_order).each do |column| %>
            <th class="column-title">
              <div class="h4" column-id='<%= column.id %>'>
                <a href="#" data-xeditable="true" data-pk="<%= column.id %>" data-model="column" data-name="name" data-url="<%= column_url(column) %>" data-title="Enter name">
                  <%= column.name %>
                </a>
                <div class="btn-group pull-right btn-group-xs">
                  <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    <span class="glyphicon glyphicon-wrench"></span> <span class="caret"></span>
                  </button>
                  <ul class="dropdown-menu" role="menu">
                    <li role="presentation" class="dropdown-header"> <%= t(:add_column) %>...</li>
                    <li>
                      <a href="#" class="add-side-column" board-id="<%= @board.id %>" side="left">
                        <span class='glyphicon glyphicon-circle-arrow-left'></span> <%= t(:to_the_left) %>
                      </a>
                    </li>
                    <li>
                      <a href="#" class="add-side-column" board-id="<%= @board.id %>" side="right">
                        <span class='glyphicon glyphicon-circle-arrow-right'></span> <%= t(:to_the_right)%>
                      </a>
                    </li>
                    <% if @board.columns.length >= 3 %>
                    <li role="presentation" class="divider"></li>
                    <li role="presentation" class="dropdown-header"><%= t(:actions) %></li>
                    <li>
                      <a href="#" class="delete-column" board-id="<%= @board.id %>" side="right">
                        <span class='glyphicon glyphicon-trash'></span> <%= t(:delete_column)%>
                      </a>
                    </li>
                    <% end %>
                  </ul>
                </div>
              </div>
            </th>
            <% end %>
          </tr>
        </thead>
        <tbody class="column_field">
          <% @board.rows.order('created_at ASC').each do |lane| %>
          <tr lane-id="<%= lane.id %>">
            <td class="lane-column">
              <button class="btn btn-xs btn-danger delete-lane" data-toggle="tooltip" data-placement="right" title="<%= t(:delete_lane_description) %>"><span class="glyphicon glyphicon-trash"> </span></button>
              <a href="#" data-xeditable="true" data-pk="<%= lane.id %>" data-model="row" data-name="name" data-url="<%= row_url(lane) %>" data-title="Enter name" style="margin-left:5px;">
                <%= lane.name %>
              </a>
              <button class="btn btn-xs btn-link delete-toggle"><span class="glyphicon glyphicon-trash"></span></button>
              <button class="btn btn-xs btn-default add-sticky" add-sticky="true" data-toggle="tooltip" data-placement="right" title="<%= t(:add_stickie_description) %>"><span class="glyphicon glyphicon-plus"> </span></button>
         
            </td> 
            <% @board.columns.order(:column_order).each do |column|%>
            <td class="column" column-id="<%= column.id %>">
              <% column.stickies.order('created_at DESC').each do |sticky| %>
              <% if lane.stickies.include?(sticky) %>
              <div class="panel animated <%= sticky.color %>" sticky-id="<%= sticky.id %>">
                <div class="panel-button"><%= sticky.link %></div>
                <div class="panel-heading"><a href="#" data-xeditable="true" data-pk="<%= sticky.id %>" data-model="sticky" data-name="name" data-url="<%= sticky_url(sticky) %>" data-title="Enter name">
                  <%= sticky.name %>
                </a>
                <i class="panel-button-mobile"><a data-toggle="modal" data-target="#stickieOptionModal" data-id="<%= sticky.id %>" class="mobile-modal"><span class="glyphicon glyphicon-cog pull-right"></span></a></i>
              </div>
              <div class="panel-body"><a href="#" data-xeditable="true" data-pk="<%= sticky.id %>" data-model="sticky" data-type="textarea" data-showbuttons="bottom" data-anim="500" data-name="text" data-url="<%= sticky_url(sticky) %>" data-title="Enter text"><%= sticky.text %></a>
              </div>
            </div>
            <% end %>
            <% end %>
          </td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
</div>