config/routes.rb
Rails.application.routes.draw do

  resources :stickies, defaults: {format: :json}

  resources :rows, defaults: {format: :json}

  resources :columns, defaults: {format: :json} do
    collection do
      post :insert_between_columns
    end
  end

  resources :boards

  get 'boards/:uid' => 'boards#index'

  get 'landing_page' => 'welcome#landing_page'

  get 'create_board' => 'boards#create_board'

  root 'welcome#landing_page'

end

app/views/layouts/_about_us.html.erb
<!-- Modal -->
<div class="modal fade" id="about_us" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel"><%= t(:about_us) %></h4>
      </div>
      <div class="modal-body">
        <%= t(:about_us_description) %>
      <br><br>
        <strong>eskra.me</strong> <small>®</small> 2014<br/>
        DCC - Universidad de Chile<br/>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="<%= root_path %>"><%=t(:home)%></a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#about"><%= t(:about_us) %></a>
                        </li>
                        <li class="footer-menu-divider">&sdot;</li>
                        <li><a href="#contact"><%=t(:contact)%></a>
                        </li>
                    </ul>
                    <p class="copyright text-muted small">Copyright &copy; eskra.me 2014. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>

app/views/layouts/_messages.html.erb
<% unless @msg_success.nil? %>
<div class="alert alert-success alert-dismissable col-xs-12 col-sm-12 col-md-6 col-md-offset-3">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong>Great!</strong> <%= @msg_success %>
</div>
<% end %>

<% unless @msg_error.nil? %>
<div class="alert alert-danger alert-dismissable col-xs-12 col-sm-12 col-md-6 col-md-offset-3">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong>Oh no!</strong> <%= @msg_error %>
</div>
<% end %>

<% unless @msg_warning.nil? %>
<div class="alert alert-warning alert-dismissable col-xs-12 col-sm-12 col-md-6 col-md-offset-3">
  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
  <strong>Watch out!</strong> <%= @msg_warning %>
</div>
<% end %>

app/views/layouts/_navbar.html.erb
<div class="container-fluid">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>"><span class="logo text-info">eskra.me</span></a>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
      <li>
        <a class="board-title" data-xeditable="true" data-pk="<%= @board.id %>" data-model="board" data-name="name" data-url="<%= board_url(@board) %>" data-title="Enter name" data-inputclass="navbar-btn" data-showbuttons="false">
            <%= @board.name %>
        </a>
      </li>
      </ul>
      <ul class="nav navbar-nav navbar-left hidden-xs">
        <div class='btn-toolbar navbar-btn'>
          <div class="btn-group" data-toggle="buttons">
            <button class="btn btn-default active toggle-collapse" data-toggle="tooltip" data-placement="bottom" title="<%= t(:toggle_view) %>">
              <span class='glyphicon glyphicon-eye-open'></span> 
            </button>
            <button class="btn btn-default active toggle-edit" data-toggle="tooltip" data-placement="bottom" title="<%= t(:toggle_edit) %>">
            <span class='glyphicon glyphicon-edit'></span> 
            </button>
          </div>
        </div>
      </ul>
      <ul class="nav navbar-nav navbar-left visible-xs">
        <li><a class="add-story" board-id="<%= @board.id %>" data-toggle="collapse" data-target="#navbar-collapse" ><span class='glyphicon glyphicon-plus'></span> 
              <span class='glyphicon glyphicon-list-alt'></span> <%= t(:add_story) %></a></li>
        <li><a class="add-column" board-id="<%= @board.id %>" data-toggle="collapse" data-target="#navbar-collapse" > <span class='glyphicon glyphicon-plus'></span> 
              <span class='glyphicon glyphicon-th-list'></span> <%= t(:add_column) %></a></li>
        <li class="divider-vertical"></li>
        <li><a class="toggle-collapse" data-toggle="collapse" data-target="#navbar-collapse" ><span class='glyphicon glyphicon-eye-open'></span>  <%= t(:toggle_view) %></a></li>
        <li><a class="toggle-edit" data-toggle="collapse" data-target="#navbar-collapse" ><span class='glyphicon glyphicon-edit'></span> <%= t(:toggle_edit) %></a></li>
        <li class="divider-vertical"></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="btn-group navbar-btn hidden-xs">
          <button class="btn btn-primary add-column" board-id="<%= @board.id %>" data-toggle="tooltip" data-placement="bottom" title="<%= t(:add_column) %>">
            <span class='glyphicon glyphicon-plus'></span> 
            <span class='glyphicon glyphicon-list-alt'></span> 
          </button>
          <button class="btn btn-success add-story"  board-id="<%= @board.id %>" data-toggle="tooltip" data-placement="bottom" title="<%= t(:add_story) %>">
            <span class='glyphicon glyphicon-plus'></span> 
            <span class='glyphicon glyphicon-th-list'></span> 
          </button>
        </li>
        <li class="dropdown hidden-xs">
          <a class="dropdown-toggle" data-toggle="dropdown"> 
            <%  case I18n.locale
                   when :en
                     language = "us"
                   when :es
                     language = "es"
                   when :jp
                     language = "jp"
                   when :zh # traditional chinese
                     language = "zh"
                end %>
            <%= image_tag "flags/" + language + ".png" , :height => "16" %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="?locale=en"> <%= image_tag "flags/us.png", :height => "16" %> &nbsp;<%= t(:english) %></a>
            </li>
            <li>
              <a href="?locale=es"> <%= image_tag "flags/es.png", :height => "16" %> &nbsp;<%= t(:spanish) %></a>
            </li>
            <li>
              <a href="?locale=jp"> <%= image_tag "flags/jp.png", :height => "16" %> &nbsp;<%= t(:japanese) %></a>
            </li>
            <li>
              <a href="?locale=zh"> <%= image_tag "flags/zh.png", :height => "16" %> &nbsp;<%= t(:chinese) %></a>
            </li>
          </ul>
        </li>

        <li class="dropdown visible-xs">
          <a class="dropdown-toggle" data-toggle="dropdown"> 
            <%= t(:choose_language) %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="?locale=en"> <%= image_tag "flags/us.png", :height => "16" %> &nbsp;<%= t(:english) %></a>
            </li>
            <li>
              <a href="?locale=es"> <%= image_tag "flags/es.png", :height => "16" %> &nbsp;<%= t(:spanish) %></a>
            </li>
            <li>
              <a href="?locale=jp"> <%= image_tag "flags/jp.png", :height => "16" %> &nbsp; <%= t(:japanese) %></a>
            </li>
            <li>
              <a href="?locale=zh"> <%= image_tag "flags/zh.png", :height => "16" %> &nbsp; <%= t(:chinese) %></a>
            </li>
          </ul>
        </li>

        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown"><%= t(:options) %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a>Share with ...</a></li>
            <li><a>Another action</a></li>
            <li><a>Something else here</a></li>
            <li class="divider"></li>
            <li><a data-toggle="modal" data-target="#about_us"><%= t(:about_us) %></a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>

app/views/layouts/_navbar_landing.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand"><span class=" logo text-info">eskra.me</span></a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"> 
            <%  case I18n.locale
            when :en
             language = "us"
           when :es
             language = "es"
           when :jp
             language = "jp"
           when :zh # traditional chinese
             language = "zh"
             end %>
             <%= image_tag "flags/" + language + ".png" , :height => "16" %> <b class="caret"></b>
           </a>
           <ul class="dropdown-menu">
            <li>
              <a href="?locale=en"> <%= image_tag "flags/us.png", :height => "16" %> &nbsp;<%= t(:english) %></a>
            </li>
            <li>
              <a href="?locale=es"> <%= image_tag "flags/es.png", :height => "16" %> &nbsp;<%= t(:spanish) %></a>
            </li>
            <li>
              <a href="?locale=jp"> <%= image_tag "flags/jp.png", :height => "16" %> &nbsp; <%= t(:japanese) %></a>
            </li>
            <li>
              <a href="?locale=zh"> <%= image_tag "flags/zh.png", :height => "16" %> &nbsp; <%= t(:chinese) %></a>
            </li>
          </ul>
        </li>
        <li><a href="#about">About</a>
        </li>
        <li><a href="#contact">Contact</a>
        </li>
      </ul>
    </div>
    <!-- /.navbar-collapse -->
  </div>
  <!-- /.container -->
</nav>

app/views/layouts/_navbar_main.html.erb
<div class="container-fluid">
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand animated pulse" href="<%= root_path %>"><span class="logo text-info">eskra.me</span></a>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse">
      <ul class="nav navbar-nav navbar-left">
      <li>
        <a class="board-title" data-xeditable="true" data-pk="<%= @board.id %>" data-model="board" data-name="name" data-url="<%= board_url(@board) %>" data-title="Enter name" data-inputclass="navbar-btn" data-showbuttons="false">
            <%= @board.name %>
        </a>
      </li>
      </ul>
      <ul class="nav navbar-nav navbar-left hidden-xs">
        <div class='btn-toolbar navbar-btn'>
          <div class="btn-group" data-toggle="buttons">
            <button class="btn btn-default active toggle-collapse" data-toggle="tooltip" data-placement="bottom" title="<%= t(:toggle_content) %>">
              <span class='glyphicon glyphicon-eye-open'></span> 
            </button>
            <button class="btn btn-default active toggle-edit" data-toggle="tooltip" data-placement="bottom" title="<%= t(:toggle_edit) %>">
            <span class='glyphicon glyphicon-edit'></span> 
            </button>
          </div>
        </div>
      </ul>
      <ul class="nav navbar-nav navbar-left visible-xs">
        <li><a class="add-lane" board-id="<%= @board.id %>" data-toggle="collapse" data-target="#navbar-collapse" ><span class='glyphicon glyphicon-plus'></span> 
              <span class='glyphicon glyphicon-list-alt'></span> <%= t(:add_lane) %></a></li>
        <li class="divider-vertical"></li>
        <li><a class="toggle-collapse" data-toggle="collapse" data-target="#navbar-collapse" ><span class='glyphicon glyphicon-eye-open'></span>  <%= t(:toggle_view) %></a></li>
        <li><a class="toggle-edit" data-toggle="collapse" data-target="#navbar-collapse" ><span class='glyphicon glyphicon-edit'></span> <%= t(:toggle_edit) %></a></li>
        <li class="divider-vertical"></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li class="btn-group navbar-btn hidden-xs">
          <button class="btn btn-primary add-lane"  board-id="<%= @board.id %>" data-toggle="tooltip" data-placement="bottom" title="<%= t(:add_lane) %>">
            <span class='glyphicon glyphicon-plus'></span> 
            <span class='glyphicon glyphicon-th-list'></span> 
          </button>
        </li>
        <li class="dropdown hidden-xs">
          <a class="dropdown-toggle" data-toggle="dropdown"> 
            <%  case I18n.locale
                   when :en
                     language = "us"
                   when :es
                     language = "es"
                   when :jp
                     language = "jp"
                   when :zh # traditional chinese
                     language = "zh"
                end %>
            <%= image_tag "flags/" + language + ".png" , :height => "16" %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="?locale=en"> <%= image_tag "flags/us.png", :height => "16" %> &nbsp;<%= t(:english) %></a>
            </li>
            <li>
              <a href="?locale=es"> <%= image_tag "flags/es.png", :height => "16" %> &nbsp;<%= t(:spanish) %></a>
            </li>
            <li>
              <a href="?locale=jp"> <%= image_tag "flags/jp.png", :height => "16" %> &nbsp;<%= t(:japanese) %></a>
            </li>
            <li>
              <a href="?locale=zh"> <%= image_tag "flags/zh.png", :height => "16" %> &nbsp;<%= t(:chinese) %></a>
            </li>
          </ul>
        </li>

        <li class="dropdown visible-xs">
          <a class="dropdown-toggle" data-toggle="dropdown"> 
            <%= t(:choose_language) %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <li>
              <a href="?locale=en"> <%= image_tag "flags/us.png", :height => "16" %> &nbsp;<%= t(:english) %></a>
            </li>
            <li>
              <a href="?locale=es"> <%= image_tag "flags/es.png", :height => "16" %> &nbsp;<%= t(:spanish) %></a>
            </li>
            <li>
              <a href="?locale=jp"> <%= image_tag "flags/jp.png", :height => "16" %> &nbsp; <%= t(:japanese) %></a>
            </li>
            <li>
              <a href="?locale=zh"> <%= image_tag "flags/zh.png", :height => "16" %> &nbsp; <%= t(:chinese) %></a>
            </li>
          </ul>
        </li>

        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown"><%= t(:options) %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
          <li role="presentation" class="dropdown-header"><%= t(:share_on) %> ...</li>
            <li><a href="https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
   target="_blank" title="Share on Facebook"><%= icon('facebook') %> Facebook</a></li>
            <li><a href="https://twitter.com/home?status=<%= request.original_url %>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;"
   target="_blank" title="Share on Twitter"><%= icon('twitter') %> Twitter</a></li>
            <li><a href="https://plus.google.com/share?url=<%= request.original_url %>" onclick="javascript:window.open(this.href, '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=350,width=480');return false;"
   target="_blank" title="Share on Google+"><%= icon('google-plus') %> Google+</a></li>
            <li class="divider"></li>
            <li><a href="#" data-toggle="modal" data-target="#about_us"><%= t(:about_us) %></a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <%= yield :title %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>

  <%= yield :head %>
  <script type="text/javascript">
  	window.I18n = <%= current_translations.to_json.html_safe %>
  </script>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>


  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>

<%= render :partial => 'layouts/navbar_main' unless controller_name == 'welcome' %>

<%= render :partial => 'layouts/navbar_landing' if controller_name == 'welcome' %>

<%= render :partial => 'layouts/messages' %>

<%= render :partial => 'layouts/about_us' %>

<%= yield %>

<%= render :partial => 'layouts/footer' %>

</body>
</html>